### ISSUE TITLE
prefix_path: No valid files found

### ISSUE THREAD

**Issue by sapema** [heart-gen/rfmix_reader#3]
Hello,

I'm trying rfmix_reader python library with a toy dataset I have but I don't figure out how prefix_path has to be to load data. I write the path directory where my input data is (local and global paths I have tried), I added the common prefix between my input files... But any of this has worked.

I post how I have written the code and how are my paths.

My code:
```
from rfmix_reader import *

prefix_path = "~/Scripts/RFMIX2-Pipeline-to-plot/Example_Dataset/RFMIX2_Output/"
binary_dir = "./binary_files"
create_binaries(prefix_path, binary_dir)

loci, rf_q, admix = read_rfmix(prefix_path)

print(loci)
print("*"*20)
print(rf_q)
print("*"*20)
print(admix)
```

Error I obtain:
```
Error: No valid files found for prefix: ~/Scripts/RFMIX2-Pipeline-to-plot/Example_Dataset/RFMIX2_Output/
Traceback (most recent call last):
  File "/home/bioevo/.local/lib/python3.10/site-packages/rfmix_reader/_utils.py", line 174, in get_prefixes
    raise FileNotFoundError()
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bioevo/Data/LA_trial/RFMix_repre.py", line 10, in <module>
    loci, rf_q, admix = read_rfmix(prefix_path)
  File "/home/bioevo/.local/lib/python3.10/site-packages/rfmix_reader/_read_rfmix.py", line 81, in read_rfmix
    fn = get_prefixes(file_prefix, verbose)
  File "/home/bioevo/.local/lib/python3.10/site-packages/rfmix_reader/_utils.py", line 180, in get_prefixes
    raise FileNotFoundError(f"No valid files found for prefix: {file_prefix}")
FileNotFoundError: No valid files found for prefix: ~/Scripts/RFMIX2-Pipeline-to-plot/Example_Dataset/RFMIX2_Output/
```

How I stored input files:
```
~/Scripts/RFMIX2-Pipeline-to-plot/Example_Dataset/RFMIX2_Output$ ls Mozabite* | head
Mozabite10_chr10.fb.tsv
Mozabite10_chr10.msp.tsv
Mozabite10_chr10.rfmix.Q
Mozabite10_chr10.sis.tsv
Mozabite10_chr11.fb.tsv
Mozabite10_chr11.msp.tsv
Mozabite10_chr11.rfmix.Q
Mozabite10_chr11.sis.tsv
Mozabite10_chr12.fb.tsv
Mozabite10_chr12.msp.tsv
```

Thank you in advance

**Comment by KrotosBenjamin** [comment]
The issue you encountered was due to a bug where the `prefix_path` was expecting to start with "^chr". This has been resolved in version 0.1.20 by implementing a more flexible pattern matching using "*_chr*". This change allows for greater compatibility with various chromosome naming conventions.

If you upgrade to version 0.1.20 or later, the problem should be resolved. The new pattern "*_chr*" will match chromosome names regardless of whether they start with "chr" or have "chr" elsewhere in the name.

If you experience any other issues after updating, or if you need further assistance, please don't hesitate to reach out.
